
import React, { useState, useEffect } from 'react';
import { Music, Frown, Smile, Sparkles, LogIn, Search, Play, PlusCircle, Check, Wand2 } from 'lucide-react';

const SPOTIFY_CLIENT_ID = '0aaa304400ff420cb9a6baef5b234231'; // Replace with your Spotify Client ID
const REDIRECT_URI = 'https://vibesync-two.vercel.app/'; // Standard Vite local port
const AUTH_ENDPOINT = "https://accounts.spotify.com/authorize";
const RESPONSE_TYPE = "token";
const SCOPES = "playlist-modify-public playlist-modify-private user-read-private";

const apiKey = "AIzaSyD_3DKnzMt8306i-5NX1ctDfT6IIILLPNM"; // Replace with your Gemini API Key

const fetchWithRetry = async (url, options, retries = 5) => {
  const delays = [1000, 2000, 4000, 8000, 16000];
  for (let i = 0; i < retries; i++) {
    try {
      const res = await fetch(url, options);
      if (!res.ok) throw new Error(`HTTP error! status: ${res.status}`);
      return res;
    } catch (error) {
      if (i === retries - 1) throw error;
      await new Promise(resolve => setTimeout(resolve, delays[i]));
    }
  }
};

export default function App() {
  const [token, setToken] = useState("");
  const [isConnected, setIsConnected] = useState(false);
  const [selectedMood, setSelectedMood] = useState(null);
  const [recommendations, setRecommendations] = useState([]);
  const [isSearching, setIsSearching] = useState(false);
  const [saveStatus, setSaveStatus] = useState("");

  const [customVibe, setCustomVibe] = useState("");
  const [isGeminiThinking, setIsGeminiThinking] = useState(false);
  const [geminiError, setGeminiError] = useState("");
  const [playlistMeta, setPlaylistMeta] = useState({ name: "", description: "" });

  useEffect(() => {
    const hash = window.location.hash;
    let localToken = window.localStorage.getItem("token");

    if (!localToken && hash) {
      localToken = hash.substring(1).split("&").find(elem => elem.startsWith("access_token")).split("=")[1];
      window.location.hash = "";
      window.localStorage.setItem("token", localToken);
    }

    if (localToken) {
      setToken(localToken);
      setIsConnected(true);
    }
  }, []);

  const handleConnect = () => {
    window.location.href = `${AUTH_ENDPOINT}?client_id=${SPOTIFY_CLIENT_ID}&redirect_uri=${REDIRECT_URI}&response_type=${RESPONSE_TYPE}&scope=${SCOPES}`;
  };

  const getRecommendations = async (mood) => {
    setSelectedMood(mood);
    setIsSearching(true);
    setRecommendations([]);
    setSaveStatus("");
    setPlaylistMeta({ name: `My ${mood} VibeSync`, description: "Generated by VibeSync" });

    if (!token) return;

    const queries = {
      sad: 'sad acoustic',
      happy: 'happy pop',
      hidden_gems: 'year:2023 tag:new'
    };

    try {
      const response = await fetch(`https://api.spotify.com/v1/search?q=${encodeURIComponent(queries[mood])}&type=track&limit=10`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      const data = await response.json();

      if (data.tracks) {
        const formattedTracks = data.tracks.items.map(track => ({
          id: track.id,
          title: track.name,
          artist: track.artists.map(a => a.name).join(', '),
          album: track.album.name,
          uri: track.uri
        }));
        setRecommendations(formattedTracks);
      }
    } catch (error) {
      console.error("Error fetching tracks:", error);
    } finally {
      setIsSearching(false);
    }
  };

  const getGeminiRecommendations = async () => {
    if (!customVibe.trim() || !token) return;

    setSelectedMood('custom');
    setIsGeminiThinking(true);
    setIsSearching(true);
    setRecommendations([]);
    setSaveStatus("");
    setGeminiError("");

    try {
      const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-09-2025:generateContent?key=${apiKey}`;
      const payload = {
        contents: [{ parts: [{ text: `The user wants to listen to music with this vibe: "${customVibe}". Generate a highly optimized Spotify search query to find 10 tracks matching this exact mood. Use Spotify search syntax like genre:, year:, or descriptive keywords. Also generate a catchy, creative playlist name and a short description.` }] }],
        systemInstruction: { parts: [{ text: "You are an expert music curator and DJ. Respond ONLY with valid JSON." }] },
        generationConfig: {
          responseMimeType: "application/json",
          responseSchema: {
            type: "OBJECT",
            properties: {
              searchQuery: { type: "STRING" },
              playlistName: { type: "STRING" },
              playlistDescription: { type: "STRING" }
            },
            required: ["searchQuery", "playlistName", "playlistDescription"]
          }
        }
      };

      const geminiRes = await fetchWithRetry(url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload)
      });
      const geminiData = await geminiRes.json();
      const aiResult = JSON.parse(geminiData.candidates[0].content.parts[0].text);

      setPlaylistMeta({ name: aiResult.playlistName, description: aiResult.playlistDescription });
      setIsGeminiThinking(false);

      const spotifyRes = await fetch(`https://api.spotify.com/v1/search?q=${encodeURIComponent(aiResult.searchQuery)}&type=track&limit=10`, {
        headers: { Authorization: `Bearer ${token}` }
      });
      const spotifyData = await spotifyRes.json();

      if (spotifyData.tracks) {
        const formattedTracks = spotifyData.tracks.items.map(track => ({
          id: track.id,
          title: track.name,
          artist: track.artists.map(a => a.name).join(', '),
          album: track.album.name,
          uri: track.uri
        }));
        setRecommendations(formattedTracks);
      }
    } catch (error) {
      console.error("Error with Gemini or Spotify:", error);
      setGeminiError("Failed to interpret your vibe. Try again.");
    } finally {
      setIsSearching(false);
      setIsGeminiThinking(false);
    }
  };

  const savePlaylist = async () => {
    if (!token || recommendations.length === 0) return;
    setSaveStatus("saving");
    try {
      const userRes = await fetch('https://api.spotify.com/v1/me', {
        headers: { Authorization: `Bearer ${token}` }
      });
      const userData = await userRes.json();

      const playlistRes = await fetch(`https://api.spotify.com/v1/users/${userData.id}/playlists`, {
        method: 'POST',
        headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({ name: playlistMeta.name, description: playlistMeta.description })
      });
      const playlistData = await playlistRes.json();

      const trackUris = recommendations.map(t => t.uri);
      await fetch(`https://api.spotify.com/v1/playlists/${playlistData.id}/tracks`, {
        method: 'POST',
        headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
        body: JSON.stringify({ uris: trackUris })
      });

      setSaveStatus("saved");
    } catch (error) {
      console.error("Error saving playlist:", error);
      setSaveStatus("error");
    }
  };

  return (
    <div className="min-h-screen bg-neutral-900 text-white font-sans p-6">
      <div className="max-w-3xl mx-auto">

        <header className="flex items-center justify-between mb-10 pb-6 border-b border-neutral-800">
          <div className="flex items-center gap-3">
            <div className="bg-green-500 p-2 rounded-full text-black">
              <Music size={24} />
            </div>
            <h1 className="text-2xl font-bold tracking-tight">VibeSync</h1>
          </div>

          {!isConnected ? (
            <button
              onClick={handleConnect}
              className="flex items-center gap-2 bg-green-500 hover:bg-green-400 text-black px-4 py-2 rounded-full font-semibold transition-colors"
            >
              <LogIn size={18} />
              Connect Spotify
            </button>
          ) : (
            <div className="flex items-center gap-3 bg-neutral-800 px-4 py-2 rounded-full">
              <img src="https://api.dicebear.com/7.x/avataaars/svg?seed=Felix" alt="User" className="w-6 h-6 rounded-full bg-neutral-700" />
              <span className="text-sm font-medium">Connected</span>
            </div>
          )}
        </header>

        {!isConnected ? (
          <div className="text-center py-20 flex flex-col items-center">
            <Music size={64} className="text-neutral-600 mb-6" />
            <h2 className="text-3xl font-bold mb-4">Discover Your Next Obsession</h2>
            <p className="text-neutral-400 mb-8 max-w-md">
              Connect your Spotify account to get highly curated track recommendations based on your exact mood or find hidden gems you've never heard before.
            </p>
          </div>
        ) : (
          <div className="space-y-8">

            <section>
              <h2 className="text-xl font-bold mb-4">What's the vibe right now?</h2>
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <button
                  onClick={() => getRecommendations('sad')}
                  className={`flex flex-col items-center justify-center gap-3 p-6 rounded-2xl border-2 transition-all ${selectedMood === 'sad' ? 'border-blue-500 bg-blue-500/10 text-blue-400' : 'border-neutral-800 bg-neutral-800 hover:bg-neutral-700 text-neutral-300'}`}
                >
                  <Frown size={32} />
                  <span className="font-medium">In My Feelings</span>
                </button>

                <button
                  onClick={() => getRecommendations('happy')}
                  className={`flex flex-col items-center justify-center gap-3 p-6 rounded-2xl border-2 transition-all ${selectedMood === 'happy' ? 'border-yellow-500 bg-yellow-500/10 text-yellow-400' : 'border-neutral-800 bg-neutral-800 hover:bg-neutral-700 text-neutral-300'}`}
                >
                  <Smile size={32} />
                  <span className="font-medium">Upbeat & Cheerful</span>
                </button>

                <button
                  onClick={() => getRecommendations('hidden_gems')}
                  className={`flex flex-col items-center justify-center gap-3 p-6 rounded-2xl border-2 transition-all ${selectedMood === 'hidden_gems' ? 'border-purple-500 bg-purple-500/10 text-purple-400' : 'border-neutral-800 bg-neutral-800 hover:bg-neutral-700 text-neutral-300'}`}
                >
                  <Sparkles size={32} />
                  <span className="font-medium">Hidden Gems</span>
                </button>
              </div>
            </section>

            <section className="bg-neutral-800/30 p-6 rounded-2xl border border-neutral-800">
              <h2 className="text-xl font-bold mb-4 flex items-center gap-2">
                <Wand2 className="text-purple-500" size={24} />
                Or describe your exact vibe
              </h2>
              <div className="flex flex-col sm:flex-row gap-3">
                <input
                  type="text"
                  value={customVibe}
                  onChange={(e) => setCustomVibe(e.target.value)}
                  placeholder="e.g. studying in a rainy Tokyo cafe, 90s grunge anger..."
                  className="flex-1 bg-neutral-900 border border-neutral-700 rounded-xl px-4 py-3 text-white placeholder-neutral-500 focus:outline-none focus:border-purple-500 focus:ring-1 focus:ring-purple-500 transition-all"
                  onKeyDown={(e) => e.key === 'Enter' && getGeminiRecommendations()}
                />
                <button
                  onClick={getGeminiRecommendations}
                  disabled={!customVibe.trim() || isSearching}
                  className="bg-purple-600 hover:bg-purple-500 disabled:opacity-50 disabled:hover:bg-purple-600 text-white px-6 py-3 rounded-xl font-semibold transition-colors flex items-center justify-center gap-2 whitespace-nowrap"
                >
                  ✨ Generate Magic Queue
                </button>
              </div>
              {geminiError && <p className="text-red-400 text-sm mt-3">{geminiError}</p>}
            </section>

            {(isSearching || recommendations.length > 0) && (
              <section className="bg-neutral-800/50 rounded-2xl p-6 border border-neutral-800">
                <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6">
                  <div>
                    <h3 className="text-lg font-semibold flex items-center gap-2">
                      {isGeminiThinking ? (
                        <>
                          <Sparkles className="animate-pulse text-purple-500" size={20} />
                          Gemini is decoding your vibe...
                        </>
                      ) : isSearching ? (
                        <>
                          <Search className="animate-pulse text-green-500" size={20} />
                          Searching Spotify...
                        </>
                      ) : (
                        <>
                          <Music className="text-green-500" size={20} />
                          {playlistMeta.name || "Your Custom Queue"}
                        </>
                      )}
                    </h3>
                    {!isSearching && selectedMood === 'custom' && playlistMeta.description && (
                      <p className="text-sm text-neutral-400 mt-1">{playlistMeta.description}</p>
                    )}
                  </div>

                  {!isSearching && recommendations.length > 0 && (
                    <button
                      onClick={savePlaylist}
                      disabled={saveStatus === "saving" || saveStatus === "saved"}
                      className="text-sm bg-neutral-700 hover:bg-neutral-600 disabled:opacity-50 px-3 py-1.5 rounded-full transition-colors flex items-center gap-1"
                    >
                      {saveStatus === "saving" ? "Saving..." : saveStatus === "saved" ? <><Check size={16} /> Saved</> : "Save as Playlist"}
                    </button>
                  )}
                </div>

                {isSearching ? (
                  <div className="space-y-3">
                    {[1, 2, 3].map((i) => (
                      <div key={i} className="h-16 bg-neutral-800 animate-pulse rounded-xl"></div>
                    ))}
                  </div>
                ) : (
                  <div className="space-y-2">
                    {recommendations.map((track) => (
                      <div key={track.id} className="group flex items-center justify-between p-3 hover:bg-neutral-700/50 rounded-xl transition-colors">
                        <div className="flex items-center gap-4">
                          <div className="w-10 h-10 bg-neutral-700 rounded-md flex items-center justify-center group-hover:bg-green-500 transition-colors cursor-pointer">
                            <Play size={16} className="text-neutral-400 group-hover:text-black ml-1" />
                          </div>
                          <div>
                            <p className="font-medium text-white">{track.title}</p>
                            <p className="text-sm text-neutral-400">{track.artist} • {track.album}</p>
                          </div>
                        </div>
                        <button className="text-neutral-400 hover:text-white p-2">
                          <PlusCircle size={20} />
                        </button>
                      </div>
                    ))}
                  </div>
                )}
              </section>
            )}

          </div>
        )}
      </div>
    </div>
  );
}